# Generated by Django 4.0.7 on 2023-07-04 14:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_copy', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_date', models.DateTimeField(default=None)),
                ('is_delay', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_returned', models.BooleanField(default=True)),
                ('blocking_end_date', models.DateTimeField(blank=True, null=True)),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='copy', to='app_copy.copy')),
            ],
        ),
    ]
