# Generated by Django 4.0.7 on 2023-07-03 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='is_retuned',
            new_name='is_returned',
        ),
    ]
