# Generated by Django 4.0.7 on 2023-07-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0006_alter_borrow_borrow_date_alter_borrow_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='is_returned',
            field=models.BooleanField(null=True),
        ),
    ]
