# Generated by Django 4.0.7 on 2023-07-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0007_alter_borrow_is_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
